### ISSUE TITLE
Autoloaded "singleton" scripts are not accessible

### ISSUE THREAD

**Issue by ohin** [AlexDarigan/WAT-GDScript#218]
In **Godot v3.3.1** with **WAT 5.0.1** autoloaded scripts are not accessible from tests. By searching WAT issues and reading through release notes I came to conclusion, that they are supposed to be accessible from tests.

I created simple project with autoloaded script and one test trying to access it. It failes.

[WAT-AutoloadsBug.zip](https://github.com/AlexDarigan/WAT-GDScript/files/6561677/WAT-AutoloadsBug.zip)

**Comment by AlexDarigan** [comment]
When I first integrated WAT directly into the Engine it had a number of problems (like this) and another user asked for Autoload Support. So I spent ages figuring out how to launch WAT as if it were a game scene automatically from the editor. Which resulted in that release note. Later I reconciled both of these contexts into two buttons.

The first play button (the white arrow to the top right of the gui) runs WAT directly in the editor. This is faster but at the expense of debugging. This is the "editor" context. It is running directly in the editor so any nodes that start in the tree (like your autoload) require tool to work for this.

The play button beside that one with the bug on it (bug for "Debug Tests") launches WAT in the game context. IE Godot is running as if it were any other game scene being run, so users don't need to give their scripts tool and they can also find problems by looking at the Godot Debugger. This is about three seconds slower though.

The reason the results show up in the same place despite which button you press is because of an internal server I created behind the scenes that talks between the the game context and WAT's gui.
